import {
  Tag,
  ShoppingCart,
  Utensils,
  Car,
  Briefcase,
  Gamepad2,
  Heart,
  Home,
  GraduationCap,
  Gift,
  Smartphone,
  Plane,
  Music,
  Dumbbell,
  Coffee,
  Baby,
  Dog,
  Wrench,
  Shirt,
  BookOpen,
  Zap,
  Wifi,
  Droplets,
  Fuel,
  Landmark,
  PiggyBank,
  TrendingUp,
  ShieldCheck,
  Stethoscope,
  Pill,
  Scissors,
  Palette,
  type LucideIcon,
} from "lucide-react"

export const ICON_MAP: Record<string, LucideIcon> = {
  Tag,
  ShoppingCart,
  Utensils,
  Car,
  Briefcase,
  Gamepad2,
  Heart,
  Home,
  GraduationCap,
  Gift,
  Smartphone,
  Plane,
  Music,
  Dumbbell,
  Coffee,
  Baby,
  Dog,
  Wrench,
  Shirt,
  BookOpen,
  Zap,
  Wifi,
  Droplets,
  Fuel,
  Landmark,
  PiggyBank,
  TrendingUp,
  ShieldCheck,
  Stethoscope,
  Pill,
  Scissors,
  Palette,
}

export const AVAILABLE_ICON_NAMES = Object.keys(ICON_MAP)

export function getIconComponent(iconName: string): LucideIcon {
  return ICON_MAP[iconName] ?? Tag
}

export const AVAILABLE_COLORS = [
  "#ef4444", "#f97316", "#eab308", "#22c55e", "#14b8a6",
  "#3b82f6", "#6366f1", "#a855f7", "#ec4899", "#f43f5e",
  "#71717a", "#0ea5e9", "#84cc16", "#d946ef", "#fb923c",
]
